"""empty message

Revision ID: bc31edc235ab
Revises: cdee2831e1c0
Create Date: 2023-04-12 21:00:38.549791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc31edc235ab'
down_revision = 'cdee2831e1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'is_looking_for_venues', new_column_name='seeking_venue')
    op.alter_column('venue', 'is_looking_for_talent', new_column_name='seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'seeking_venue', new_column_name='is_looking_for_venues')
    op.alter_column('venue', 'seeking_talent', new_column_name='is_looking_for_talent')
    # ### end Alembic commands ###
